### ISSUE TITLE
Mockup of bird tracking explorer version 2

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#39]
![image](https://cloud.githubusercontent.com/assets/600993/4233909/5623a9c0-39b1-11e4-8a91-cf3647159385.png)

**Comment by bartaelterman** [comment]
I don't think the selection needs to be cleared when navigating the year chart. The selected cell is highlighted and nicely moves along with the chart. The `selected-time` element still displays the selection. A `clear selection` button will be implemented later, so the user can clear the selection if he wants to.
Have a look at the current status (checkout this commit c7c4148 or later)
In fact, seeing it live now, I think clearing the selection might even surprise the user.

**Comment by bartaelterman** [comment]
As mentioned in #49 I don't see a way to select a year. That raises the following questions:

- What do we show by default in 5 - 9 when selecting a bird?
- If you want to show one year after loading a new bird, how do you define a year? Last 12 months of data?
- Note that as requested in #43 the year chart might not show a full year on smaller screens. We cannot assume that 12 months will be displayed. Hence, it might be weird to load 12 months of data in the other charts.

**Comment by peterdesmet** [comment]
* Ok on `clear selection`. Best to make an task issue for this.
* Regarding year: can you detect how many months are shown in the "year" chart? If so, maybe we can use that as a default?
