### ISSUE TITLE
Add birds in select-bird dropdown

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#41]
Use [bird_tracking_devices](https://lifewatch-inbo.cartodb.com/tables/bird_tracking_devices) to populate the dropdown `select-bird` https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55260181 with all bird names. They should be grouped per species in `<optgroup>`s and sorted alphabetically.

## Tasks

* [x] Populate
* [x] Bird name
* [x] Sorted
* [x] [Optgroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup)
* [x] Optgroup label = scientific name

## Example

    Larus fuscus
    - Eric
    - Michelle
    - Misja

**Comment by bartaelterman** [comment]
Fixed: 9b046ca47d332722316772fbbf18dfa51fe76abc
