### ISSUE TITLE
Fix alignment of day labels in month chart

### ISSUE THREAD

**Issue by bartaelterman** [LifeWatchINBO/bird-tracking#59]
The labels of the domains are vertically not properly aligned. After playing with the html in Chrome, I noticed that setting the attribute `dominant-baseline` to `text-after-edge` solves this issue. By default, this attribute is set to `top` by cal-heatmap. I don't know where that happens, but adding this to our `main.css` does not fix it. Probably the css is overridden by the javascript when it creates the elements. Need to find a way to fix this.

**Comment by peterdesmet** [comment]
Since we have a tooltip, I think we can work with a `month` domain and not have any labels/legend at all

**Comment by bartaelterman** [comment]
Hmm... You should try it on the running application. A visual clue would really make it easier to explore the data. I already kind of 'miss' labels on the year chart when I'm testing.

**Comment by bartaelterman** [comment]
Parameter in cal-heatmap found that fixes this.
