### ISSUE TITLE
Overflow hidden causes tooltip to be cut off

### ISSUE THREAD

**Issue by bartaelterman** [LifeWatchINBO/bird-tracking#60]
The `overflow: hidden` we defined for the yearchart in the css causes the tooltip of the yearchart to be cut off. How can we fix this?

**Comment by peterdesmet** [comment]
We can't fix it: http://stackoverflow.com/questions/8837050/allow-specific-tag-to-override-overflowhidden. Is the number of months to be displayed (based on the available width) calculated for each selection of a bird? If so, I would just remove `overflow` and not provide a fix for horizontal window resizing.
