### ISSUE TITLE
Fix legend scale of month heatmap

### ISSUE THREAD

**Issue by bartaelterman** [LifeWatchINBO/bird-tracking#66]
The legend scale of the month heatmap is currently set equal to the scale of the year heatmap. However, the year chart sums the number of kilometers travelled per day, which is always much more then the numbers displayed in the month heatmap. Therefore, the month heatmap lacks contrast which could be improved with a separate scale.

**Comment by bartaelterman** [comment]
@peterdesmet what's your opinion on this?

**Comment by peterdesmet** [comment]
As mentioned, I don't think a legend is required.

**Comment by bartaelterman** [comment]
This is merely an issue about the scale, not about the legend. I'll rephrase the question:

Look at december 2013 drawn in the year chart for bird Jozef:

![screen shot 2015-05-19 at 11 11 06](https://cloud.githubusercontent.com/assets/2742677/7699405/f82abb0c-fe17-11e4-8b8d-dbdad77cf65a.png)

3 Different colors are used. One for less then 10 km travelled, one for between 10 and 20 and one for between 20 and 30. The legend defines two additional categories: between 30 and 40 and more then 40. Cal-heatmap defines these categories automatically, based on the input data, but you can set them yourself. (which could make sense for the yearchart alone because the latter category is used to display days where 41 kilometer was travelled as well as days where 341 kilometer was travelled).

The problem I'm pointing out here however is that when using two cal-heatmap charts on one page, cal-heatmap will use the same scale by default. That means that for the month chart, the same categories are used. This doesn't make sense in our case. You don't expect distances by hour (as displayed in the month chart) to be of the same order of magnitude as distances by day (as displayed in the year chart). The fact that the month chart uses the categories of the year chart results in boring and uninformative month charts. Here is the month chart for that december 2013 again:

![screen shot 2015-05-19 at 11 11 20](https://cloud.githubusercontent.com/assets/2742677/7699616/62297c5e-fe19-11e4-8d6d-e724e7d58457.png)

Ok, Jozef was relatively inactive in december compared to other months, but that's what the year chart should (and does) show. The month chart should show the hours within a given month, that Jozef was active. To achieve this, the month chart should use it's own categories to color the hours and it should not use the categories defined by the year chart.

**Comment by peterdesmet** [comment]
I see. Yes, I agree they should use different scales. Is that technically possible?

**Comment by bartaelterman** [comment]
I'm investigating it.

**Comment by bartaelterman** [comment]
In b9444680e5d2f3952a6b99b9e48e812876eb2948 I let the two functions define their own categories based on the data they will plot. The month chart simply defines 5 categories by dividing the range of the data by 5 (so the categories are evenly distributed).
I was not happy with that procedure for the year chart however. The year chart contains many high outliers. A dumb solution was to divide the range of the data by 10, and use the first 5 categories. (so the 5 highest categories are merged into one big category). It is a bit arbitrary, and some additional tuning might be needed, but I'm pleased with the result.

**Comment by peterdesmet** [comment]
Probably OK for now. If you want to use dynamic scales based on the data, it might be good to compare clustering methods: equal, quantile, jenks, etc.
